name: Pages
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Checkout branch
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Checkout base torillic
      uses: actions/checkout@v3
      with:
        repository: TEParsons/torillic
        ref: main
        path: base

    - name: Inject base Torillic
      run: |
        python base/utils/stub.py

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-awesome-pages-plugin
        pip install .

    - name: Build
      run: |
        mkdocs build

    - name: Commit
      run: |
        git config --global user.email "todd.e.parsons@googlemail.com"
        git config --global user.name "Todd Parsons"
        git add --all
        git commit --all -m "Build"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
